def display_rainbow
  red = "R"
  orange = "O"
  yellow = "Y"
  green = "G"
  blue = "B"
  indigo = "I"
  violet = "V"
  puts "R is #{red}"
  puts "O is #{orange}"
  puts "Y is #{yellow}"
  puts "G is #{green}"
  puts "B is #{blue}"
  puts "I is #{indigo}"
  puts "V is #{violet}"
end
